[package]
name = "shard"
version = "1.0.0"
edition = "2021"
authors = ["Saphereye <adarshdas950@gmail.com>"]

[dependencies]
chess = "3.2.0"
clap = { version = "4.5.18", features = ["derive"] }
rand = "0.8.5"
