[package]
name = "shard"
version = "4.4.0"
edition = "2021"
authors = ["Saphereye <adarshdas950@gmail.com>"]

[dependencies]
chess = "3.2.0"
nom = "7.1.3"
timecat = { version = "1.45.6", default-features = false, features = ["inbuilt_nnue"] }

[profile.release]
debug = true
