[package]
name = "shard"
version = "4.1.0"
edition = "2021"
authors = ["Saphereye <adarshdas950@gmail.com>"]

[dependencies]
chess = "3.2.0"
nom = "7.1.3"
rand = "0.8.5"
rayon = "1.10.0"

[profile.release]
debug = true
